# 训练参数设置
import torch

batch_size = 128
num_epochs = 10
learning_rate = 1E-3

# 超参数设置
IMAGE_SIZE = torch.tensor([28, 28])
PADDING_SIZE = torch.tensor([2, 2])
CONV1_OUTPUT_CHANNELS = 16
CONV2_OUTPUT_CHANNELS = 32
DILATION = 1
KERNEL_SIZE = torch.tensor([3, 3])
KERNEL_STRIDE = 2
POOL_SIZE = torch.tensor([2, 2])
POOL_STRIDE = 1

# 通过超参数计算参数
CONV_OUTPUT_SIZE_1 = (IMAGE_SIZE + 2 * PADDING_SIZE - DILATION * (KERNEL_SIZE - 1) - 1) // KERNEL_STRIDE + 1

POOL_OUTPUT_SIZE_1 = (CONV_OUTPUT_SIZE_1 - POOL_SIZE + 1) // POOL_STRIDE

CONV_OUTPUT_SIZE_2 = (POOL_OUTPUT_SIZE_1 + 2 * PADDING_SIZE - DILATION * (KERNEL_SIZE - 1) - 1) // KERNEL_STRIDE + 1

POOL_OUTPUT_SIZE_2 = (CONV_OUTPUT_SIZE_2 - POOL_SIZE + 1) // POOL_STRIDE

FC_INPUT_SIZE = CONV2_OUTPUT_CHANNELS * int(POOL_OUTPUT_SIZE_2[0] * POOL_OUTPUT_SIZE_2[1])